name: Pull requests

on:
  pull_request:
    branches:
      - '**'

jobs:

  build_job:
    name: Build Pull Request
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
          run: ./gradlew build