/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kiwix_kiwixlib_Filter */

#ifndef _Included_org_kiwix_kiwixlib_Filter
#define _Included_org_kiwix_kiwixlib_Filter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    local
 * Signature: (Z)Lorg/kiwix/kiwixlib/Filter;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_Filter_local
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    remote
 * Signature: (Z)Lorg/kiwix/kiwixlib/Filter;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_Filter_remote
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    valid
 * Signature: (Z)Lorg/kiwix/kiwixlib/Filter;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_Filter_valid
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    acceptTags
 * Signature: ([Ljava/lang/String;)Lorg/kiwix/kiwixlib/Filter;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_Filter_acceptTags
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    rejectTags
 * Signature: ([Ljava/lang/String;)Lorg/kiwix/kiwixlib/Filter;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_Filter_rejectTags
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    lang
 * Signature: (Ljava/lang/String;)Lorg/kiwix/kiwixlib/Filter;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_Filter_lang
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    publisher
 * Signature: (Ljava/lang/String;)Lorg/kiwix/kiwixlib/Filter;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_Filter_publisher
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    creator
 * Signature: (Ljava/lang/String;)Lorg/kiwix/kiwixlib/Filter;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_Filter_creator
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    maxSize
 * Signature: (J)Lorg/kiwix/kiwixlib/Filter;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_Filter_maxSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    query
 * Signature: (Ljava/lang/String;)Lorg/kiwix/kiwixlib/Filter;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_Filter_query
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    allocate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_Filter_allocate
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Filter
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_Filter_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
