/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kiwix_kiwixlib_Library */

#ifndef _Included_org_kiwix_kiwixlib_Library
#define _Included_org_kiwix_kiwixlib_Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kiwix_kiwixlib_Library
 * Method:    addBook
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kiwix_kiwixlib_Library_addBook
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_Library
 * Method:    getBookById
 * Signature: (Ljava/lang/String;)Lorg/kiwix/kiwixlib/Book;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_Library_getBookById
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_Library
 * Method:    getBookCount
 * Signature: (ZZ)I
 */
JNIEXPORT jint JNICALL Java_org_kiwix_kiwixlib_Library_getBookCount
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     org_kiwix_kiwixlib_Library
 * Method:    getBooksIds
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_kiwix_kiwixlib_Library_getBooksIds
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Library
 * Method:    filter
 * Signature: (Lorg/kiwix/kiwixlib/Filter;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_kiwix_kiwixlib_Library_filter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Library
 * Method:    getBooksLanguages
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_kiwix_kiwixlib_Library_getBooksLanguages
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Library
 * Method:    getBooksCreators
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_kiwix_kiwixlib_Library_getBooksCreators
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Library
 * Method:    getBooksPublishers
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_kiwix_kiwixlib_Library_getBooksPublishers
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Library
 * Method:    allocate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_Library_allocate
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Library
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_Library_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
