/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kiwix_kiwixlib_JNIKiwixReader */

#ifndef _Included_org_kiwix_kiwixlib_JNIKiwixReader
#define _Included_org_kiwix_kiwixlib_JNIKiwixReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getMainPage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getMainPage
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getTitle
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getId
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getLanguage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getLanguage
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getMimeType
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getMimeType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    checkUrl
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_checkUrl
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getContent
 * Signature: (Lorg/kiwix/kiwixlib/JNIKiwixString;Lorg/kiwix/kiwixlib/JNIKiwixString;Lorg/kiwix/kiwixlib/JNIKiwixString;Lorg/kiwix/kiwixlib/JNIKiwixInt;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getContent
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getContentPart
 * Signature: (Ljava/lang/String;IILorg/kiwix/kiwixlib/JNIKiwixInt;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getContentPart
  (JNIEnv *, jobject, jstring, jint, jint, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getArticleSize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getArticleSize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getDirectAccessInformation
 * Signature: (Ljava/lang/String;)Lorg/kiwix/kiwixlib/DirectAccessInfo;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getDirectAccessInformation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    searchSuggestions
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_searchSuggestions
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getNextSuggestion
 * Signature: (Lorg/kiwix/kiwixlib/JNIKiwixString;Lorg/kiwix/kiwixlib/JNIKiwixString;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getNextSuggestion
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getPageUrlFromTitle
 * Signature: (Ljava/lang/String;Lorg/kiwix/kiwixlib/JNIKiwixString;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getPageUrlFromTitle
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getDescription
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getDate
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getFavicon
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getFavicon
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getCreator
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getCreator
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getPublisher
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getPublisher
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getName
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getFileSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getFileSize
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getArticleCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getArticleCount
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getMediaCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getMediaCount
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getRandomPage
 * Signature: (Lorg/kiwix/kiwixlib/JNIKiwixString;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getRandomPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getNativeReader
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getNativeReader
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getNativeReaderByFD
 * Signature: (Ljava/io/FileDescriptor;)J
 */
JNIEXPORT jlong JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getNativeReaderByFD
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixReader
 * Method:    getNativeReaderEmbedded
 * Signature: (Ljava/io/FileDescriptor;JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_kiwix_kiwixlib_JNIKiwixReader_getNativeReaderEmbedded
  (JNIEnv *, jobject, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
