/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kiwix_kiwixlib_Book */

#ifndef _Included_org_kiwix_kiwixlib_Book
#define _Included_org_kiwix_kiwixlib_Book
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    update
 * Signature: (Lorg/kiwix/kiwixlib/Book;)V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_Book_update__Lorg_kiwix_kiwixlib_Book_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    update
 * Signature: (Lorg/kiwix/kiwixlib/JNIKiwixReader;)V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_Book_update__Lorg_kiwix_kiwixlib_JNIKiwixReader_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getId
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getPath
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    isPathValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_kiwix_kiwixlib_Book_isPathValid
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getTitle
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getDescription
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getLanguage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getLanguage
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getCreator
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getCreator
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getPublisher
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getPublisher
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getDate
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getUrl
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getName
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getFlavour
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getFlavour
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getCategory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getCategory
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getTags
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getTags
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getTagStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getTagStr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getArticleCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_kiwix_kiwixlib_Book_getArticleCount
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getMediaCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_kiwix_kiwixlib_Book_getMediaCount
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_kiwix_kiwixlib_Book_getSize
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getFavicon
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getFavicon
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getFaviconUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getFaviconUrl
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    getFaviconMimeType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kiwix_kiwixlib_Book_getFaviconMimeType
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    allocate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_Book_allocate
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_Book
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_Book_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
