/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kiwix_kiwixlib_JNIKiwixSearcher */

#ifndef _Included_org_kiwix_kiwixlib_JNIKiwixSearcher
#define _Included_org_kiwix_kiwixlib_JNIKiwixSearcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixSearcher
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_JNIKiwixSearcher_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixSearcher
 * Method:    getNativeHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_kiwix_kiwixlib_JNIKiwixSearcher_getNativeHandle
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixSearcher
 * Method:    addReader
 * Signature: (Lorg/kiwix/kiwixlib/JNIKiwixReader;)V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_JNIKiwixSearcher_addReader
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixSearcher
 * Method:    search
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_JNIKiwixSearcher_search
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixSearcher
 * Method:    getNextResult
 * Signature: ()Lorg/kiwix/kiwixlib/JNIKiwixSearcher/Result;
 */
JNIEXPORT jobject JNICALL Java_org_kiwix_kiwixlib_JNIKiwixSearcher_getNextResult
  (JNIEnv *, jobject);

/*
 * Class:     org_kiwix_kiwixlib_JNIKiwixSearcher
 * Method:    hasMoreResult
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_kiwix_kiwixlib_JNIKiwixSearcher_hasMoreResult
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
