/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kiwix_kiwixlib_JNIICU */

#ifndef _Included_org_kiwix_kiwixlib_JNIICU
#define _Included_org_kiwix_kiwixlib_JNIICU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kiwix_kiwixlib_JNIICU
 * Method:    setDataDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kiwix_kiwixlib_JNIICU_setDataDirectory
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
